server:
  port: 25000

spring:
  application:
    name: gulimall-seckill

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

  redis:
    host: 192.168.142.5
    port: 6379
  rabbitmq:
    host: 192.168.142.5
    username: itcast
    password: 123321
    listener:
      simple:
        acknowledge-mode: manual
  #链路追踪
  zipkin:
    # zipkin 服务器的地址
    base-url: http://192.168.142.5:9411/
    # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

  session:
    store-type: redis



management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug



