spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.142.5:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 192.168.142.5
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        #nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719

  rabbitmq:
    host: 192.168.142.5
    username: itcast
    password: 123321
    listener:
      simple:
        acknowledge-mode: manual
  #链路追踪
  zipkin:
    # zipkin 服务器的地址
    base-url: http://192.168.142.5:9411/
    # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9000

# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300

management:
  endpoints:
    web:
      exposure:
        include: '*'