server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    host: 192.168.142.5
  session:
    store-type: redis
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/

logging:
  level:
    com.codeofli.gulimall.search.service: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'