server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    host: 192.168.142.5
  session:
    store-type: redis
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  #链路追踪
  zipkin:
    # zipkin 服务器的地址
    base-url: http://192.168.142.5:9411/
    # 关闭服务发现，否则Spring Cloud 会把zipkin 的url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为100%，默认为0.1，即10%
logging:
  level:
    com.codeofli.gulimall.search.service: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'